# Generated by Django 5.1 on 2024-08-28 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('value', models.CharField(blank=True, choices=[('O', 'O'), ('X', 'X')], max_length=1)),
            ],
        ),
    ]
