# Generated by Django 5.1 on 2024-08-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='value',
        ),
        migrations.AddField(
            model_name='cell',
            name='content',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cell',
            name='col',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cell',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='row',
            field=models.IntegerField(),
        ),
    ]
