# Generated by Django 5.1 on 2024-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0003_alter_cell_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='King',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('player', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
    ]
