# Generated by Django 5.1 on 2024-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0004_king_delete_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='king',
            name='move_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='king',
            name='player',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
