# Generated by Django 5.1 on 2024-09-01 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0005_king_move_count_alter_king_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('right', models.IntegerField()),
                ('left', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='King',
            new_name='Board',
        ),
    ]
