# Generated by Django 5.1 on 2024-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0006_deckcard_rename_king_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('player', models.CharField(blank=True, max_length=10, null=True)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='move_count',
        ),
        migrations.AddField(
            model_name='board',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
