# Generated by Django 5.1 on 2024-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0007_actionlog_remove_board_move_count_board_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=10, null=True)),
                ('knight_count', models.IntegerField()),
            ],
        ),
    ]
