# Generated by Django 5.1 on 2024-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0008_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='is_card_drawn',
            field=models.BooleanField(default=False),
        ),
    ]
