# Generated by Django 5.1 on 2024-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0009_deckcard_is_card_drawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
