# Generated by Django 5.1 on 2024-09-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose', '0011_knight'),
    ]

    operations = [
        migrations.AddField(
            model_name='knight',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='board_count',
            field=models.IntegerField(default=0),
        ),
    ]
