# Generated by Django 5.1 on 2024-08-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('value', models.CharField(blank=True, choices=[('O', 'O'), ('X', 'X')], max_length=1)),
            ],
            options={
                'unique_together': {('row', 'col')},
            },
        ),
    ]
